name: Build and Publish FrettysEssentia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  GenerateArtifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build and Generate Artifacts
        run: docker build -t frettysessentia .
          
      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: FrettysEssentia
          path: .
